/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Załóż konto organizera */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Dawid Patko",
                     *       "email": "dawid@example.com",
                     *       "password": "tajnehaslo123",
                     *       "passwordConfirmation": "tajnehaslo123"
                     *     }
                     */
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        password: string;
                        passwordConfirmation: string;
                    };
                };
            };
            responses: {
                /** @description Konto założone, token wydany */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "token": "1|4bT9xQkR7fN2wUhLpVmZ",
                         *         "user": {
                         *           "id": 1,
                         *           "name": "Dawid Patko",
                         *           "email": "dawid@example.com",
                         *           "createdAt": "2026-09-01T10:00:00+02:00"
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["AuthPayload"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zaloguj się */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "dawid@example.com",
                     *       "password": "tajnehaslo123"
                     *     }
                     */
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Token wydany */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "token": "1|4bT9xQkR7fN2wUhLpVmZ",
                         *         "user": {
                         *           "id": 1,
                         *           "name": "Dawid Patko",
                         *           "email": "dawid@example.com",
                         *           "createdAt": "2026-09-01T10:00:00+02:00"
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["AuthPayload"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unieważnij bieżący token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Wylogowano */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zalogowany organizer
         * @description Używane przy starcie panelu do odtworzenia sesji z zapisanego tokenu.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dane konta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "name": "Dawid Patko",
                         *         "email": "dawid@example.com",
                         *         "createdAt": "2026-09-01T10:00:00+02:00"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista sportów wraz z konfiguracją
         * @description Panel korzysta z `config`, żeby wiedzieć, jakie rodzaje zdarzeń, tiebreaki
         *     i statystyki są dopuszczalne dla danego sportu. Backend waliduje to samo
         *     po swojej stronie: lista na froncie jest wygodą, nie zabezpieczeniem.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sporty predefiniowane w systemie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "code": "football",
                         *           "name": "Piłka nożna",
                         *           "config": {
                         *             "allowsDraw": true,
                         *             "defaultPoints": {
                         *               "win": 3,
                         *               "draw": 1,
                         *               "loss": 0
                         *             },
                         *             "eventTypes": [
                         *               {
                         *                 "code": "goal",
                         *                 "label": "Bramka",
                         *                 "hasPlayer": true,
                         *                 "stat": "goals"
                         *               },
                         *               {
                         *                 "code": "own_goal",
                         *                 "label": "Bramka samobójcza",
                         *                 "hasPlayer": true,
                         *                 "stat": null
                         *               },
                         *               {
                         *                 "code": "yellow_card",
                         *                 "label": "Żółta kartka",
                         *                 "hasPlayer": true,
                         *                 "stat": "yellowCards"
                         *               },
                         *               {
                         *                 "code": "red_card",
                         *                 "label": "Czerwona kartka",
                         *                 "hasPlayer": true,
                         *                 "stat": "redCards"
                         *               }
                         *             ],
                         *             "availableTiebreakers": [
                         *               "points",
                         *               "head_to_head",
                         *               "goal_diff",
                         *               "goals_for",
                         *               "wins"
                         *             ],
                         *             "availableStats": [
                         *               "goals",
                         *               "yellowCards",
                         *               "redCards"
                         *             ]
                         *           }
                         *         },
                         *         {
                         *           "id": 2,
                         *           "code": "basketball",
                         *           "name": "Koszykówka",
                         *           "config": {
                         *             "allowsDraw": false,
                         *             "defaultPoints": {
                         *               "win": 2,
                         *               "draw": 0,
                         *               "loss": 1
                         *             },
                         *             "eventTypes": [
                         *               {
                         *                 "code": "points",
                         *                 "label": "Punkty",
                         *                 "hasPlayer": true,
                         *                 "stat": "points"
                         *               },
                         *               {
                         *                 "code": "foul",
                         *                 "label": "Faul",
                         *                 "hasPlayer": true,
                         *                 "stat": "fouls"
                         *               }
                         *             ],
                         *             "availableTiebreakers": [
                         *               "points",
                         *               "head_to_head",
                         *               "goal_diff",
                         *               "goals_for",
                         *               "wins"
                         *             ],
                         *             "availableStats": [
                         *               "points",
                         *               "fouls"
                         *             ]
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Sport"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turnieje zalogowanego organizera */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stronicowana lista turniejów */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "name": "Liga Osiedlowa 2026",
                         *           "slug": "liga-osiedlowa-2026",
                         *           "status": "active",
                         *           "sport": {
                         *             "id": 1,
                         *             "code": "football",
                         *             "name": "Piłka nożna"
                         *           },
                         *           "branding": {
                         *             "logoUrl": null,
                         *             "primaryColor": "#1F7A45"
                         *           },
                         *           "points": {
                         *             "win": 3,
                         *             "draw": 1,
                         *             "loss": 0
                         *           },
                         *           "tiebreakers": [
                         *             "points",
                         *             "head_to_head",
                         *             "goal_diff",
                         *             "goals_for"
                         *           ],
                         *           "teamsCount": 10,
                         *           "createdAt": "2026-09-01T10:00:00+02:00",
                         *           "updatedAt": "2026-09-14T18:30:00+02:00"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "Puchar Zimowy",
                         *           "slug": "puchar-zimowy",
                         *           "status": "draft",
                         *           "sport": {
                         *             "id": 2,
                         *             "code": "basketball",
                         *             "name": "Koszykówka"
                         *           },
                         *           "branding": {
                         *             "logoUrl": null,
                         *             "primaryColor": "#1F7A45"
                         *           },
                         *           "points": {
                         *             "win": 2,
                         *             "draw": 0,
                         *             "loss": 1
                         *           },
                         *           "tiebreakers": [
                         *             "points",
                         *             "head_to_head",
                         *             "goal_diff"
                         *           ],
                         *           "teamsCount": 8,
                         *           "createdAt": "2026-09-10T09:00:00+02:00",
                         *           "updatedAt": "2026-09-10T09:00:00+02:00"
                         *         }
                         *       ],
                         *       "meta": {
                         *         "currentPage": 1,
                         *         "lastPage": 1,
                         *         "perPage": 20,
                         *         "total": 2
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Tournament"][];
                            meta: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        /**
         * Załóż turniej
         * @description `format` nie jest zapisywanym polem turnieju, tylko wskazówką, jakie fazy
         *     (`Stage`) utworzyć przy zakładaniu. Po utworzeniu prawdą o strukturze
         *     turnieju są wyłącznie jego fazy.
         *
         *     `slug` jest generowany z nazwy i można go później zmienić.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Liga Osiedlowa 2026",
                     *       "sportId": 1,
                     *       "format": "league"
                     *     }
                     */
                    "application/json": components["schemas"]["TournamentCreate"];
                };
            };
            responses: {
                /** @description Turniej założony */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "name": "Liga Osiedlowa 2026",
                         *         "slug": "liga-osiedlowa-2026",
                         *         "status": "draft",
                         *         "sport": {
                         *           "id": 1,
                         *           "code": "football",
                         *           "name": "Piłka nożna"
                         *         },
                         *         "branding": {
                         *           "logoUrl": null,
                         *           "primaryColor": "#1F7A45"
                         *         },
                         *         "points": {
                         *           "win": 3,
                         *           "draw": 1,
                         *           "loss": 0
                         *         },
                         *         "tiebreakers": [
                         *           "points",
                         *           "head_to_head",
                         *           "goal_diff",
                         *           "goals_for"
                         *         ],
                         *         "teamsCount": 0,
                         *         "createdAt": "2026-09-01T10:00:00+02:00",
                         *         "updatedAt": "2026-09-01T10:00:00+02:00"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Tournament"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        /** Szczegóły turnieju */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Turniej */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "name": "Liga Osiedlowa 2026",
                         *         "slug": "liga-osiedlowa-2026",
                         *         "status": "active",
                         *         "sport": {
                         *           "id": 1,
                         *           "code": "football",
                         *           "name": "Piłka nożna"
                         *         },
                         *         "branding": {
                         *           "logoUrl": null,
                         *           "primaryColor": "#1F7A45"
                         *         },
                         *         "points": {
                         *           "win": 3,
                         *           "draw": 1,
                         *           "loss": 0
                         *         },
                         *         "tiebreakers": [
                         *           "points",
                         *           "head_to_head",
                         *           "goal_diff",
                         *           "goals_for"
                         *         ],
                         *         "teamsCount": 10,
                         *         "createdAt": "2026-09-01T10:00:00+02:00",
                         *         "updatedAt": "2026-09-14T18:30:00+02:00"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Tournament"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Usuń turniej */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usunięto */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Zmień ustawienia turnieju
         * @description Obsługuje też zmianę kolejności tiebreaków (`tiebreakers`) i zmianę
         *     `slug`. Zmiana `slug` unieważnia dotychczasowy publiczny adres turnieju:
         *     panel musi o tym ostrzec przed zapisem.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Liga Osiedlowa 2026/27",
                     *       "tiebreakers": [
                     *         "points",
                     *         "goal_diff",
                     *         "head_to_head",
                     *         "goals_for"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["TournamentUpdate"];
                };
            };
            responses: {
                /** @description Turniej po zmianie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Tournament"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/tournaments/{tournament}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wgraj logo turnieju */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        logo: string;
                    };
                };
            };
            responses: {
                /** @description Turniej z nowym logo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Tournament"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        /**
         * Fazy turnieju
         * @description Turniej ma zawsze co najmniej jedną fazę, także gdy jest zwykłą ligą.
         *     Endpointy zapisu dla faz wchodzą w v0.2 razem z silnikiem rozgrywek.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fazy wraz z grupami */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "type": "league",
                         *           "name": "Faza zasadnicza",
                         *           "order": 1,
                         *           "groups": []
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Stage"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        /** Drużyny w turnieju */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pełna lista drużyn, bez stronicowania */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "tournamentId": 1,
                         *           "name": "Wilki Bemowo",
                         *           "logoUrl": null,
                         *           "groupId": null
                         *         },
                         *         {
                         *           "id": 2,
                         *           "tournamentId": 1,
                         *           "name": "Sokoły Ursus",
                         *           "logoUrl": null,
                         *           "groupId": null
                         *         },
                         *         {
                         *           "id": 3,
                         *           "tournamentId": 1,
                         *           "name": "Orły Bielany",
                         *           "logoUrl": null,
                         *           "groupId": null
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Team"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Dodaj drużynę */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Wilki Bemowo"
                     *     }
                     */
                    "application/json": {
                        name: string;
                        /** Format: int64 */
                        groupId?: number | null;
                    };
                };
            };
            responses: {
                /** @description Drużyna dodana */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "tournamentId": 1,
                         *         "name": "Wilki Bemowo",
                         *         "logoUrl": null,
                         *         "groupId": null
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Team"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        /** Szczegóły drużyny */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Drużyna */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "tournamentId": 1,
                         *         "name": "Wilki Bemowo",
                         *         "logoUrl": null,
                         *         "groupId": null
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Team"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Usuń drużynę
         * @description Odrzucane z kodem `422`, jeżeli drużyna wystąpiła w rozegranym meczu:
         *     usunięcie zmieniłoby tabelę wstecz.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usunięto */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        options?: never;
        head?: never;
        /** Zmień drużynę */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: int64 */
                        groupId?: number | null;
                    };
                };
            };
            responses: {
                /** @description Drużyna po zmianie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Team"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/teams/{team}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wgraj herb drużyny */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        logo: string;
                    };
                };
            };
            responses: {
                /** @description Drużyna z nowym herbem */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Team"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team}/players": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        /** Zawodnicy drużyny */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pełna lista zawodników, bez stronicowania */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "teamId": 1,
                         *           "name": "Marek Nowak",
                         *           "number": 9,
                         *           "position": "napastnik"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "teamId": 1,
                         *           "name": "Piotr Kowal",
                         *           "number": 1,
                         *           "position": "bramkarz"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Player"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Dodaj zawodnika */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Marek Nowak",
                     *       "number": 9,
                     *       "position": "napastnik"
                     *     }
                     */
                    "application/json": {
                        name: string;
                        number?: number | null;
                        position?: string | null;
                    };
                };
            };
            responses: {
                /** @description Zawodnik dodany */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "teamId": 1,
                         *         "name": "Marek Nowak",
                         *         "number": 9,
                         *         "position": "napastnik"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Player"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player: components["parameters"]["PlayerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Usuń zawodnika */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    player: components["parameters"]["PlayerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usunięto */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        options?: never;
        head?: never;
        /** Zmień zawodnika */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    player: components["parameters"]["PlayerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        number?: number | null;
                        position?: string | null;
                    };
                };
            };
            responses: {
                /** @description Zawodnik po zmianie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Player"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/tournaments/{tournament}/venues": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        /** Obiekty w turnieju */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pełna lista obiektów, bez stronicowania */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "tournamentId": 1,
                         *           "name": "Boisko Bemowo",
                         *           "address": "ul. Powstańców Śląskich 1, Warszawa"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "tournamentId": 1,
                         *           "name": "Hala Ursus",
                         *           "address": "ul. Sosnkowskiego 3, Warszawa"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Venue"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Dodaj obiekt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Boisko Bemowo",
                     *       "address": "ul. Powstańców Śląskich 1, Warszawa"
                     *     }
                     */
                    "application/json": {
                        name: string;
                        address?: string | null;
                    };
                };
            };
            responses: {
                /** @description Obiekt dodany */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "tournamentId": 1,
                         *         "name": "Boisko Bemowo",
                         *         "address": "ul. Powstańców Śląskich 1, Warszawa"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Venue"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venue}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Usuń obiekt */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venue: components["parameters"]["VenueId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usunięto */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        options?: never;
        head?: never;
        /** Zmień obiekt */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venue: components["parameters"]["VenueId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        address?: string | null;
                    };
                };
            };
            responses: {
                /** @description Obiekt po zmianie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Venue"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/tournaments/{tournament}/matches": {
        parameters: {
            query?: {
                stageId?: number;
                roundId?: number;
                status?: components["schemas"]["MatchStatus"];
            };
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        /**
         * Mecze turnieju
         * @description Odczyt. Wpisywanie wyniku i zmiana stanu meczu wchodzą w v0.2, ale kształt
         *     `Match` jest już zamrożony.
         */
        get: {
            parameters: {
                query?: {
                    stageId?: number;
                    roundId?: number;
                    status?: components["schemas"]["MatchStatus"];
                };
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mecze, opcjonalnie zawężone parametrami */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "stageId": 1,
                         *           "groupId": null,
                         *           "round": {
                         *             "id": 1,
                         *             "name": "Kolejka 1",
                         *             "order": 1
                         *           },
                         *           "homeTeam": {
                         *             "id": 1,
                         *             "name": "Wilki Bemowo",
                         *             "logoUrl": null
                         *           },
                         *           "awayTeam": {
                         *             "id": 2,
                         *             "name": "Sokoły Ursus",
                         *             "logoUrl": null
                         *           },
                         *           "homeScore": 2,
                         *           "awayScore": 1,
                         *           "status": "finished",
                         *           "kickoffAt": "2026-09-06T12:00:00+02:00",
                         *           "venue": {
                         *             "id": 1,
                         *             "name": "Boisko Bemowo"
                         *           },
                         *           "nextMatchId": null,
                         *           "bracketSlot": null
                         *         },
                         *         {
                         *           "id": 2,
                         *           "stageId": 1,
                         *           "groupId": null,
                         *           "round": {
                         *             "id": 2,
                         *             "name": "Kolejka 2",
                         *             "order": 2
                         *           },
                         *           "homeTeam": {
                         *             "id": 3,
                         *             "name": "Orły Bielany",
                         *             "logoUrl": null
                         *           },
                         *           "awayTeam": {
                         *             "id": 1,
                         *             "name": "Wilki Bemowo",
                         *             "logoUrl": null
                         *           },
                         *           "homeScore": null,
                         *           "awayScore": null,
                         *           "status": "scheduled",
                         *           "kickoffAt": "2026-09-13T12:00:00+02:00",
                         *           "venue": null,
                         *           "nextMatchId": null,
                         *           "bracketSlot": null
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Match"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament: components["parameters"]["TournamentId"];
            };
            cookie?: never;
        };
        /**
         * Tabele turnieju
         * @description Tabela nie jest bytem zapisywanym: jest liczona przy każdym odczycie
         *     z zakończonych meczów. Jedna pozycja na fazę `league` i jedna na każdą
         *     grupę w fazie `group`. Faza `knockout` nie ma tabeli.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tabele w kolejności faz */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "stageId": 1,
                         *           "stageName": "Faza zasadnicza",
                         *           "groupId": null,
                         *           "groupName": null,
                         *           "rows": [
                         *             {
                         *               "position": 1,
                         *               "team": {
                         *                 "id": 1,
                         *                 "name": "Wilki Bemowo",
                         *                 "logoUrl": null
                         *               },
                         *               "played": 2,
                         *               "won": 2,
                         *               "drawn": 0,
                         *               "lost": 0,
                         *               "goalsFor": 5,
                         *               "goalsAgainst": 1,
                         *               "goalDifference": 4,
                         *               "points": 6
                         *             },
                         *             {
                         *               "position": 2,
                         *               "team": {
                         *                 "id": 2,
                         *                 "name": "Sokoły Ursus",
                         *                 "logoUrl": null
                         *               },
                         *               "played": 2,
                         *               "won": 1,
                         *               "drawn": 0,
                         *               "lost": 1,
                         *               "goalsFor": 3,
                         *               "goalsAgainst": 3,
                         *               "goalDifference": 0,
                         *               "points": 3
                         *             },
                         *             {
                         *               "position": 3,
                         *               "team": {
                         *                 "id": 3,
                         *                 "name": "Orły Bielany",
                         *                 "logoUrl": null
                         *               },
                         *               "played": 2,
                         *               "won": 0,
                         *               "drawn": 0,
                         *               "lost": 2,
                         *               "goalsFor": 1,
                         *               "goalsAgainst": 5,
                         *               "goalDifference": -4,
                         *               "points": 0
                         *             }
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["StandingTable"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/t/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /** Publiczna strona turnieju */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["Slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Turniej w wersji publicznej */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "name": "Liga Osiedlowa 2026",
                         *         "slug": "liga-osiedlowa-2026",
                         *         "status": "active",
                         *         "sport": {
                         *           "id": 1,
                         *           "code": "football",
                         *           "name": "Piłka nożna"
                         *         },
                         *         "branding": {
                         *           "logoUrl": null,
                         *           "primaryColor": "#1F7A45"
                         *         },
                         *         "stages": [
                         *           {
                         *             "id": 1,
                         *             "type": "league",
                         *             "name": "Faza zasadnicza",
                         *             "order": 1,
                         *             "groups": []
                         *           }
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["PublicTournament"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/t/{slug}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /** Tabele turnieju */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["Slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tabele */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "stageId": 1,
                         *           "stageName": "Faza zasadnicza",
                         *           "groupId": null,
                         *           "groupName": null,
                         *           "rows": [
                         *             {
                         *               "position": 1,
                         *               "team": {
                         *                 "id": 1,
                         *                 "name": "Wilki Bemowo",
                         *                 "logoUrl": null
                         *               },
                         *               "played": 2,
                         *               "won": 2,
                         *               "drawn": 0,
                         *               "lost": 0,
                         *               "goalsFor": 5,
                         *               "goalsAgainst": 1,
                         *               "goalDifference": 4,
                         *               "points": 6
                         *             },
                         *             {
                         *               "position": 2,
                         *               "team": {
                         *                 "id": 2,
                         *                 "name": "Sokoły Ursus",
                         *                 "logoUrl": null
                         *               },
                         *               "played": 2,
                         *               "won": 1,
                         *               "drawn": 0,
                         *               "lost": 1,
                         *               "goalsFor": 3,
                         *               "goalsAgainst": 3,
                         *               "goalDifference": 0,
                         *               "points": 3
                         *             }
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["StandingTable"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/t/{slug}/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /** Terminarz (mecze jeszcze nierozegrane) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["Slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mecze o stanie innym niż zakończony, rosnąco po terminie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 2,
                         *           "stageId": 1,
                         *           "groupId": null,
                         *           "round": {
                         *             "id": 2,
                         *             "name": "Kolejka 2",
                         *             "order": 2
                         *           },
                         *           "homeTeam": {
                         *             "id": 3,
                         *             "name": "Orły Bielany",
                         *             "logoUrl": null
                         *           },
                         *           "awayTeam": {
                         *             "id": 1,
                         *             "name": "Wilki Bemowo",
                         *             "logoUrl": null
                         *           },
                         *           "homeScore": null,
                         *           "awayScore": null,
                         *           "status": "scheduled",
                         *           "kickoffAt": "2026-09-13T12:00:00+02:00",
                         *           "venue": null,
                         *           "nextMatchId": null,
                         *           "bracketSlot": null
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Match"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/t/{slug}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /** Wyniki (mecze zakończone) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["Slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mecze zakończone, malejąco po terminie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "stageId": 1,
                         *           "groupId": null,
                         *           "round": {
                         *             "id": 1,
                         *             "name": "Kolejka 1",
                         *             "order": 1
                         *           },
                         *           "homeTeam": {
                         *             "id": 1,
                         *             "name": "Wilki Bemowo",
                         *             "logoUrl": null
                         *           },
                         *           "awayTeam": {
                         *             "id": 2,
                         *             "name": "Sokoły Ursus",
                         *             "logoUrl": null
                         *           },
                         *           "homeScore": 2,
                         *           "awayScore": 1,
                         *           "status": "finished",
                         *           "kickoffAt": "2026-09-06T12:00:00+02:00",
                         *           "venue": {
                         *             "id": 1,
                         *             "name": "Boisko Bemowo"
                         *           },
                         *           "nextMatchId": null,
                         *           "bracketSlot": null
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["Match"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/t/{slug}/top-scorers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Klasyfikacja indywidualna
         * @description Statystyka, według której budowana jest klasyfikacja, zależy od sportu
         *     (bramki w piłce, punkty w koszykówce), dlatego odpowiedź niesie jej kod
         *     i etykietę zamiast zakładać, że chodzi o bramki.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["Slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Klasyfikacja zawodników */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "stat": "goals",
                         *         "label": "Bramki",
                         *         "rows": [
                         *           {
                         *             "position": 1,
                         *             "player": {
                         *               "id": 1,
                         *               "name": "Marek Nowak"
                         *             },
                         *             "team": {
                         *               "id": 1,
                         *               "name": "Wilki Bemowo",
                         *               "logoUrl": null
                         *             },
                         *             "value": 4
                         *           },
                         *           {
                         *             "position": 2,
                         *             "player": {
                         *               "id": 5,
                         *               "name": "Adam Zieliński"
                         *             },
                         *             "team": {
                         *               "id": 2,
                         *               "name": "Sokoły Ursus",
                         *               "logoUrl": null
                         *             },
                         *             "value": 2
                         *           }
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["StatLeaderboard"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        ValidationError: {
            message: string;
            errors: {
                [key: string]: string[];
            };
        };
        PaginationMeta: {
            currentPage: number;
            lastPage: number;
            perPage: number;
            total: number;
        };
        User: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuthPayload: {
            token: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        SportCode: "football" | "basketball";
        Points: {
            win: number;
            draw: number;
            loss: number;
        };
        SportEventType: {
            code: string;
            label: string;
            /** @description Czy zdarzenie wymaga wskazania zawodnika. */
            hasPlayer: boolean;
            /** @description Kod statystyki, do której zdarzenie się wlicza. `null` oznacza zdarzenie bez wpływu na statystyki. */
            stat: string | null;
        };
        SportConfig: {
            /** @description Czy w tym sporcie mecz może zakończyć się remisem. */
            allowsDraw: boolean;
            defaultPoints: components["schemas"]["Points"];
            eventTypes: components["schemas"]["SportEventType"][];
            availableTiebreakers: components["schemas"]["TiebreakerCode"][];
            availableStats: string[];
        };
        Sport: {
            /** Format: int64 */
            id: number;
            code: components["schemas"]["SportCode"];
            name: string;
            config: components["schemas"]["SportConfig"];
        };
        SportSummary: {
            /** Format: int64 */
            id: number;
            code: components["schemas"]["SportCode"];
            name: string;
        };
        /**
         * @description Kryterium rozstrzygające o kolejności w tabeli. `points` jest zawsze
         *     pierwsze na liście turnieju. `head_to_head` porównuje wyłącznie mecze
         *     między remisującymi drużynami i nie zagłębia się rekurencyjnie: gdy nie
         *     rozstrzyga, stosowane jest następne kryterium z listy.
         * @enum {string}
         */
        TiebreakerCode: "points" | "head_to_head" | "goal_diff" | "goals_for" | "goals_against" | "wins";
        /** @enum {string} */
        TournamentStatus: "draft" | "active" | "finished";
        /**
         * @description Używane wyłącznie przy zakładaniu turnieju, żeby wiedzieć jakie fazy
         *     utworzyć. Nie jest polem turnieju: strukturę opisują fazy.
         * @enum {string}
         */
        TournamentFormat: "league" | "groups_playoff" | "knockout";
        Branding: {
            /** Format: uri */
            logoUrl: string | null;
            primaryColor: string;
        };
        Tournament: {
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
            status: components["schemas"]["TournamentStatus"];
            sport: components["schemas"]["SportSummary"];
            branding: components["schemas"]["Branding"];
            /** @description Punktacja obowiązująca w tym turnieju, wyjściowo skopiowana z domyślnej dla sportu. */
            points: components["schemas"]["Points"];
            /** @description Uporządkowana lista kryteriów, stosowanych po kolei. */
            tiebreakers: components["schemas"]["TiebreakerCode"][];
            teamsCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TournamentCreate: {
            name: string;
            /** Format: int64 */
            sportId: number;
            format: components["schemas"]["TournamentFormat"];
        };
        TournamentUpdate: {
            name?: string;
            slug?: string;
            status?: components["schemas"]["TournamentStatus"];
            primaryColor?: string;
            points?: components["schemas"]["Points"];
            tiebreakers?: components["schemas"]["TiebreakerCode"][];
        };
        /**
         * @description `league` to jedna tabela, `group` to kilka niezależnych tabel,
         *     `knockout` to drabinka. Turniej ma zawsze co najmniej jedną fazę.
         * @enum {string}
         */
        StageType: "league" | "group" | "knockout";
        Group: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        Stage: {
            /** Format: int64 */
            id: number;
            type: components["schemas"]["StageType"];
            name: string;
            order: number;
            /** @description Niepuste wyłącznie dla fazy `group`. */
            groups: components["schemas"]["Group"][];
        };
        /**
         * @description Uporządkowany zbiór meczów rozgrywanych razem. W fazie `league` i `group`
         *     nazywany w interfejsie kolejką, w fazie `knockout` rundą. W API to jeden byt.
         */
        RoundSummary: {
            /** Format: int64 */
            id: number;
            name: string;
            order: number;
        };
        Team: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            tournamentId: number;
            name: string;
            /** Format: uri */
            logoUrl: string | null;
            /**
             * Format: int64
             * @description Grupa w fazie `group`. `null`, gdy turniej nie ma fazy grupowej.
             */
            groupId: number | null;
        };
        TeamSummary: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: uri */
            logoUrl: string | null;
        };
        Player: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            teamId: number;
            name: string;
            number: number | null;
            position: string | null;
        };
        PlayerSummary: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        Venue: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            tournamentId: number;
            name: string;
            address: string | null;
        };
        VenueSummary: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        /**
         * @description Tylko mecz `finished` wpływa na tabelę i statystyki.
         * @enum {string}
         */
        MatchStatus: "scheduled" | "live" | "finished";
        Match: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            stageId: number;
            /**
             * Format: int64
             * @description Grupa, w ramach której mecz się liczy. `null` poza fazą `group`. Nie istnieje mecz międzygrupowy.
             */
            groupId: number | null;
            round: components["schemas"]["RoundSummary"];
            /** @description `null`, gdy miejsce w drabince nie jest jeszcze rozstrzygnięte. Pauza (bye) w lidze nieparzystej **nie** tworzy meczu — kolejka ma po prostu o jeden mecz mniej. */
            homeTeam: components["schemas"]["TeamSummary"] | null;
            awayTeam: components["schemas"]["TeamSummary"] | null;
            homeScore: number | null;
            awayScore: number | null;
            status: components["schemas"]["MatchStatus"];
            /** Format: date-time */
            kickoffAt: string | null;
            venue: components["schemas"]["VenueSummary"] | null;
            /**
             * Format: int64
             * @description Mecz, do którego awansuje zwycięzca. Tylko w fazie `knockout`.
             */
            nextMatchId: number | null;
            /** @description Pozycja w drabince, na przykład `SF1-home`. Tylko w fazie `knockout`. */
            bracketSlot: string | null;
        };
        StandingRow: {
            position: number;
            team: components["schemas"]["TeamSummary"];
            played: number;
            won: number;
            drawn: number;
            lost: number;
            goalsFor: number;
            goalsAgainst: number;
            goalDifference: number;
            points: number;
        };
        StandingTable: {
            /** Format: int64 */
            stageId: number;
            stageName: string;
            /** Format: int64 */
            groupId: number | null;
            groupName: string | null;
            rows: components["schemas"]["StandingRow"][];
        };
        StatLeaderboardRow: {
            position: number;
            player: components["schemas"]["PlayerSummary"];
            team: components["schemas"]["TeamSummary"];
            value: number;
        };
        StatLeaderboard: {
            /** @description Kod statystyki, zgodny z `availableStats` sportu. */
            stat: string;
            label: string;
            rows: components["schemas"]["StatLeaderboardRow"][];
        };
        PublicTournament: {
            name: string;
            slug: string;
            status: components["schemas"]["TournamentStatus"];
            sport: components["schemas"]["SportSummary"];
            branding: components["schemas"]["Branding"];
            stages: components["schemas"]["Stage"][];
        };
    };
    responses: {
        /** @description Brak lub nieważny token */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Unauthenticated."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Zasób należy do innego organizera */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "This action is unauthorized."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Zasób nie istnieje */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Nie znaleziono zasobu."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Dane nie przeszły walidacji */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Podane dane są nieprawidłowe.",
                 *       "errors": {
                 *         "name": [
                 *           "Pole nazwa jest wymagane."
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        TournamentId: number;
        TeamId: number;
        PlayerId: number;
        VenueId: number;
        Slug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
